### ISSUE TITLE
Support to require certain roles using nextjs middleware

### ISSUE THREAD

**Issue by mr-bjerre** [supabase-community/auth-helpers#103]
Currently we can do the do the following to protect routes via middleware

```typescript
import { withMiddlewareAuth } from "@supabase/supabase-auth-helpers/nextjs/middleware";

export const middleware = withMiddlewareAuth({ redirectTo: "/login" });
```

However I'd like to restrict certain routes for certain roles; e.g. admins only. I keep track of my admins in a table so it is basically a question of reading data from the database and require some condition based on that. Any suggestion on how to achieve that?

**Comment by mr-bjerre** [comment]
We could add an option to provide a user callback to determine if a user is allowed or not.

So extend the parameter options to this

```typescript
export interface withMiddlewareAuthOptions {
  redirectTo?: string;
  cookieOptions?: CookieOptions;
  tokenRefreshMargin?: number;
  permissionGuard?: {
    isPermitted: (user: User) => boolean
    redirectTo: string;
  }
}
```

And then add the following line before returning

```typescript
if (permissionGuard && permissionGuard.isPermitted(authResult.user)) {
    throw new Error('User is not permitted, redirecting');
}
```

We then have to update the error handling to handle two different type of errors (since it needs to redirect to different paths).

If you think this is viable then I'll put together a PR - let me know.

**Comment by ferpintado** [comment]
This is a case that I am running into, will be very helpful for sure

**Comment by mr-bjerre** [comment]
Simarily we could do something similar on [`withApiAuth`](https://github.com/supabase-community/supabase-auth-helpers/blob/main/src/nextjs/README.md#protecting-api-routes). I'm waiting for the maintainers to comment/accept #104  before "copying" the solution over.

**Comment by silentworks** [comment]
PR for this was merged and will be out in the next release.
