### ISSUE TITLE
`user` is undefined, returned from `useUser` in `1.4.2`

### ISSUE THREAD

**Issue by glekner** [supabase-community/auth-helpers#106]
Since `1.4.2`, after trying to login, `useUser` returns `undefined` for `user`.
running `supabaseClient.auth.user()` does returns a user.

downgrading to `1.4.1` solves the problem

**Comment by silentworks** [comment]
This library will no longer be maintained and I would advice you migrate to [@supabase/auth-helpers-nextjs](https://www.npmjs.com/package/@supabase/auth-helpers-nextjs) instead.
