### ISSUE TITLE
Doesnt work with deno?

### ISSUE THREAD

**Issue by joshhubers** [supabase-community/auth-helpers#116]
Hello, thanks for the great package.

Unfortunately I seem to be having issues using this package with `deno`. It looks like there's some sort of issue with the `jose` library and maybe _its_ compatibility with `deno`.

When I attempt to include the `nextjs` helpers via es module and `deno run` I get a package resolution issue.

`import { supabaseClient } from "https://esm.sh/@supabase/supabase-auth-helpers@1.4.2/nextjs";`

`deno run` produces:

```
error: Uncaught SyntaxError: The requested module 'https://deno.land/std@0.141.0/node/zlib.ts' does not provide an export named 'inflateRaw'
    at <anonymous> (https://esm.sh/v85/jose@4.8.1/deno/jose.js:2:11728)
```

**Comment by joshhubers** [comment]
I tried to fork and replace the package with a different dependency, but I had trouble building a distribution / es module that matches the distributed package.

**Comment by silentworks** [comment]
Can you provide a test repo that reproduces this issue so we can address it? we chose `jose` because it stated it would work in a `deno` environment, but if this isn't the case we can look at using `worktop/jwt` instead.
