### ISSUE TITLE
/api/auth/callback almost never gets called in Safari

### ISSUE THREAD

**Issue by GustavEkberg** [supabase-community/auth-helpers#118]
When logging in on Safari, no matter if it's mobile or desktop. /api/auth/callback *almost* never gets called and the user won't get logged in. Randomly it works though.
Here are 2 screenshots of the network communication in Safari, one for a working flow and one for an not working one:
Not working:
![image](https://user-images.githubusercontent.com/5611464/171635443-91b71925-0617-454c-9f8f-b76b25aeffba.png)
Working:
![image](https://user-images.githubusercontent.com/5611464/171635477-45ba1504-21ca-4480-a673-5ceade51ce00.png)

Chrome and every other browser work fine.

Login implementation:
![image](https://user-images.githubusercontent.com/5611464/171635589-d1daf350-994f-49ea-964c-51515d4e8336.png)

SignInOAuthButton:
![image](https://user-images.githubusercontent.com/5611464/171635672-7143de86-fb13-47ee-a0df-dc9410ea5a3e.png)

Is this a known issue?

**Comment by silentworks** [comment]
Can you provide an example repo reproducing this issue for us to take a look at?

**Comment by silentworks** [comment]
Can you provide an example repo reproducing this issue for us to take a look at?

**Comment by GustavEkberg** [comment]
Invited you to the repo in question. @silentworks

**Comment by silentworks** [comment]
@GustavEkberg do you have a more minimal project showing this issue as this one requires me to have a database schema setup (I can't find a .sql file in the repo) and it has many moving parts to it.

**Comment by silentworks** [comment]
This issue is inactive, closing.
