### ISSUE TITLE
resolve(event) called twice in sveltekit-auth-helpers

### ISSUE THREAD

**Issue by david-plugge** [supabase-community/auth-helpers#123]
A silent refresh does not set the new cookies.

https://github.com/supabase-community/supabase-auth-helpers/blob/cb78247bec510f9d8aefa32d5a17ff17a01bec7b/packages/sveltekit/src/handlers/user.ts#L50

**Comment by silentworks** [comment]
What is a silent refresh? how can I reproduce the issue you are seeing?

**Comment by david-plugge** [comment]
I´ve set up a selfhosted supabase instance and set the token lifetime to 90 seconds to test if the refreshing works.

If the user is authenticated and the token is expired a new token is issued on the next request.
However, the new tokens are not set in the cookies.

The cookies are applied to the headers of `res`, but `res` is never send to the client.
```ts
const res = await resolve(event);
const response = await getUser({ req, res }, { cookieOptions, tokenRefreshMargin });
event.locals.user = response.user;
event.locals.accessToken = response.accessToken;
return await resolve(event);
```

**Comment by silentworks** [comment]
This should now be fixed in the latest release as we are only resolving the event once. https://github.com/supabase-community/auth-helpers/commit/d23b2683abf2e40eeefdac8b10c215d46b01e4c5#diff-285358224e2d89ba4bfca835d5416b9ef97cb98ad9ed62348bf34eff4f56783dR46-R51
