### ISSUE TITLE
Auth helpers doesn't set local storage item (supabase.auth.token)

### ISSUE THREAD

**Issue by y3owk1n** [supabase-community/auth-helpers#125]
Hi everyone,

I am just wondering for some reason, when I am signing in according to the nextjs example, it doesn't save the **supabase.auth.token** in the localstorage. I am just wondering if this is true or not.

I do get the cookies stored properly.
<img width="180" alt="image" src="https://user-images.githubusercontent.com/62775956/172390808-c9d9903b-b207-460e-8cdd-923ccbe4855d.png">

However, the localstorage is empty.
<img width="412" alt="image" src="https://user-images.githubusercontent.com/62775956/172390960-54eacc27-d425-4bfa-9a28-eceb62abcb8b.png">

 For now, I am setting the local storage manually upon login and removing it upon logging out.. Any help from all the experts here would be much appreciated!

**Comment by silentworks** [comment]
This is the correct behaviour. The auth helper library saves the tokens to cookies instead and uses that when making requests.
