### ISSUE TITLE
auth-helpers-sveltekit – Error: <SuperUserHelper> is not a valid SSR component.

### ISSUE THREAD

**Issue by finnstrand** [supabase-community/auth-helpers#127]
I've followed the instructions here in the docs on Github and get this error:

```Error: <SuperUserHelper> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules```

Anyone experienced this and/or know how to solve it?

**Comment by ogrotten** [comment]
After digging around, i found that the exported component is actually called `SupaAuthHelper` instead of the instructed `SuperUserHelper`

**Comment by finnstrand** [comment]
🙏 Haha, yeah I was also confused about why it would be called `SuperUserHelper`
