### ISSUE TITLE
Svelte auth helpers have no provider_token strategy

### ISSUE THREAD

**Issue by elliottetzkorn** [supabase-community/auth-helpers#139]
I see no way to fetch the `provider_token` using the new Svelte helper code and example application. Can this functionality be added please.

**Comment by silentworks** [comment]
This is saved in a cookie when using the `auth-helpers-sveltekit` library and can be retrieved from the cookies. You can take a look in the example code to see how it is done https://github.com/supabase-community/auth-helpers/blob/develop/examples/sveltekit/src/routes/github-provider-token.ts#L12-L13

**Comment by silentworks** [comment]
I've added a `getProviderToken` method to the `0.6.6` release which only requires the request object and it will return the token once you are logged in.

**Comment by elliottetzkorn** [comment]
Thanks @silentworks
