### ISSUE TITLE
Redirect user to protected page after logged in?

### ISSUE THREAD

**Issue by hoangvu12** [supabase-community/auth-helpers#140]
Is there anyway to redirect the user back to the protected page after logged in?

For example we have `/protected`, and user is not logged in, when user navigate to `/protected`, it will redirect user to `/login` . After logged in, user will be redirected back to `/protected`, which is the page user was trying to navigate into.

**Comment by Robert-Nickel** [comment]
I would love to see this feature too.

**Comment by david-plugge** [comment]
You can just add a query param like `redirectTo=/protected` to your `/login` redirect and after login check for that param and send the user to that route.

**Comment by hoangvu12** [comment]
> You can just add a query param like `redirectTo=/protected` to your `/login` redirect and after login check for that param and send the user to that route.

Yes I could do that, but it would be nice if the helpers handle them already ;D

**Comment by silentworks** [comment]
This should be handled by the application developer themselves and not this library.

**Comment by hoangvu12** [comment]
I've tried to accomplish this *feature* but can't seem to work. I passed `redirectedTo` param to supabase signin, but after logged in, it redirected to my production website

![image](https://user-images.githubusercontent.com/68330291/184952912-9b49ab04-bcbc-4cac-918f-0c10126e177f.png)

Turn out I have to add redirect urls on supabase dashboard, which is not really cool because there are a lot of pages and I can't add them one by one (also there are dynamic pages).

Is there anyway to do this?

**Comment by silentworks** [comment]
Add a wildcard to the dashboard `https://yourwebsite.com/**` and that will redirect to any page on your website. Please don't do this with localhost:3000 when you are making your website live.

**Comment by hoangvu12** [comment]
> Add a wildcard to the dashboard `https://yourwebsite.com/**` and that will redirect to any page on your website. Please don't do this with localhost:3000 when you are making your website live.

Thank you, that worked.

**Comment by hoangvu12** [comment]
I tried on production and it didn't work, although it worked fine in development. 



> Add a wildcard to the dashboard `https://yourwebsite.com/**` and that will redirect to any page on your website. Please don't do this with localhost:3000 when you are making your website live.

![image_2022-08-18_072430563](https://user-images.githubusercontent.com/68330291/185266106-a0fb0f8c-124b-4e12-aa63-c2e69f39d9f8.png)
