### ISSUE TITLE
Where can I find the docs for this project?

### ISSUE THREAD

**Issue by lumenwrites** [supabase-community/auth-helpers#141]
There used to be a [file](https://github.com/supabase-community/auth-helpers/blob/_archive-supabase-auth-helpers/src/nextjs/README.md) explaining how to use this library, can you help me find the most up to date version of it? Where should I go to see all the docs explaining how to use this library?

**Comment by silentworks** [comment]
This is now located inside each package's README.md. We should probably link it from the main README.md to make it easier to find https://github.com/supabase-community/auth-helpers/blob/main/packages/nextjs/README.md
