### ISSUE TITLE
How can I avoid fetching data from my database twice, first to get the logged in auth.user, then to fetch their data from my own profile table where I keep their data?

### ISSUE THREAD

**Issue by lumenwrites** [supabase-community/auth-helpers#149]
Hi! I'm building a Next.js app with Supabase, using this library. I have two tables, `auth.users` managed by Supabase Auth, and `Profile`, where I keep all the custom data I want to save about the users.

Currently, to make the data from `Profile` available in my app, I have to make two requests to the database:
1. First one made by `useUser()` function from `'@supabase/auth-helpers-react'`, to fetch the id of the logged in user.
2. Second one is made by me, to use the user id to fetch the data from my profile info.

The first request seems unnecessary, since all I need is to get user.id from cookies managed by Supabase Auth. Is there any way for me to avoid making this request? Can this library help me with that? Can you share some advice on how to correctly handle this?

Here's how my current data fetching code looks like, inside my auth context:

```javascript
  // Next helpers automatically fetch the logged in user info
  const { user: helpersUser, error } = useUser()
  // My own user, containing the info I fetched from the Profile table
  const [user, setUser] = useState()
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    async function getUserProfile() {
      const { data: profile } = await supabaseClient
        .from('Profile')
        .select('*')
        .eq('id', helpersUser.id)
        .single()
      console.log('[AuthContext] Fetched profile data', profile)
      // Combine data from supabase auth table, with data from profile
      setUser({ ...helpersUser, ...profile })
      setIsLoading(false)
    }
    // Only fetch profile info once user is logged in.
    if (helpersUser) {
      getUserProfile()
    }
    if (error) {
      console.log('[AuthContext] Login error', error)
      setIsLoading(false)
    }
  }, [helpersUser, error])
```

I have to do something similar on the backend:
```javascript
export async function getServerSideProps({ params, req, res }) {
  const { user } = await getUser({ req, res }) // Access the user object

  if (user) { // if the user is logged in, fetch their profile info
    const profile = await prisma.profile.findUnique({
      where: { id: user.id },
      include: { boughtCourses: true },
    })
   [...]
  }
  [...]
}
```

Can you help me find the right way to avoid doing that as well?

**Comment by MildTomato** [comment]
This is a little off topic, but something to maybe consider might be using row level security to restrict users from only reading their own profile, especially if it's private
https://supabase.com/docs/guides/auth/managing-user-data#private-access

Screenshot of the type of policy required

<img width="1210" alt="Screenshot 2022-06-29 at 6 21 34 PM" src="https://user-images.githubusercontent.com/8291514/176413919-af0f975d-f1fd-41b0-b800-d0ed966006b2.png">

**Comment by silentworks** [comment]
Please ask this question on the [GitHub discussions](https://github.com/supabase/supabase/discussions) for Supabase or on the Supabase [discord](https://discord.supabase.com/) as it's an issue with the library itself.
