### ISSUE TITLE
NextJS - withPageAuth not working correctly ?

### ISSUE THREAD

**Issue by Jordaneisenburger** [supabase-community/auth-helpers#167]
Not sure if this is a bug or intended behavior. The scenario is the following: 

**Happy path:** User requests login link -> user clicks link in email  -> gets redirected to the domain.com/dashboard
**What's actually happening:** User requests login link -> user clicks link in email  -> gets redirected to the domain.com/login

if I manually go to /dashboard it works and shows the logged-in user. But when the user clicks the link in the email (which has a proper redirect url attached) see https://jfmtgdhboxggbuxzlxmq.supabase.co/auth/v1/verify?token=hzlojssrmeugovxcxukd&type=magiclink&redirect_to=http://localhost:3001/dashboard it redirects to /login# (not sure why it adds the # at the end)

The code at the protected page
```
// pages/dashboard/index.js
import React from 'react';
import { withPageAuth } from '@supabase/auth-helpers-nextjs';
import { useUser } from '@supabase/auth-helpers-react';

const Dashboard = () => {
    const { user, error } = useUser();

    return (
        <h1>Hello {user?.email}</h1>
    )
}

export const getServerSideProps = withPageAuth({ redirectTo: '/login' });

export default Dashboard

```

Not sure why this happens but any guidance it appreciated, thanks!

**Comment by eekrain** [comment]
Im also experiencing this as well. Even with their own examples, i cloned it and do yarn install and select the latest version of auth-helpers-nextjs and react, and it can't even get the user state using useUser.

**Comment by silentworks** [comment]
I've described this issue and a workaround in another thread https://github.com/supabase-community/auth-helpers/issues/150#issuecomment-1171663367 I will try and create a NextJS example showing how to do this at some point.

**Comment by Jordaneisenburger** [comment]
> I've described this issue and a workaround in another thread [#150 (comment)](https://github.com/supabase-community/auth-helpers/issues/150#issuecomment-1171663367) I will try and create a NextJS example showing how to do this at some point.

@silentworks thanks! I understand the work around just wondering if this is actually the way to go with supabase auth
