### ISSUE TITLE
<SupaAuthHelper> is not a valid SSR component

### ISSUE THREAD

**Issue by 24jr** [supabase-community/auth-helpers#186]
Issue for sveltekit following guide. 

<SupaAuthHelper> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules

Idk if one of these sortve things in svelte.config.js also idk if new way with vite 3 doesnt use svelte.config.js cause I got some kind of error trying this and I dont even know if this is correct way
```
import adapter from '@sveltejs/adapter-auto';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    adapter: adapter()
    // vite: {
    //   ssr: {
    //     noExternal: ['@supabase/auth-helpers-sveltekit']
    //   }
    // }
  }
};

export default config;

```

**Comment by 24jr** [comment]
<img width="546" alt="Screen Shot 2022-07-18 at 10 54 44 PM" src="https://user-images.githubusercontent.com/34662182/179654426-4134e709-0134-4fb7-946b-1e37b9f5e548.png">
So SupaAuthHelper is an export right? If i do `  import * as test from '@supabase/auth-helpers-sveltekit';	
  console.log('test',test)`  it doesnt show SupaAuthHelper in that which I think it should so maybe not even getting exported to be available

**Comment by silentworks** [comment]
Please take a look at the readme, this is exported from a different package called `@supabase/auth-helpers-svelte` not `@supabase/auth-helpers-sveltekit`. You are trying to import from the wrong package. You can see this working in the example projects.
