### ISSUE TITLE
sveltekit-email-password -no possibility to sign up

### ISSUE THREAD

**Issue by kvetoslavnovak** [supabase-community/auth-helpers#193]
I have quite a difficult time with the sveltekit-email-password example as there is no sing up option The sign in (index) page has no usage because there is no way to add a user in this example in the first place.  Would be great to have sign up route as well.
To overcome this limitation I had to use the invitation button in the Supabase project dashboard  itself to create a new user. 
:-(

**Comment by silentworks** [comment]
I've added this to the example in commit efbbfff9a9864d301e08eef2353b0bb26d33f9b3

**Comment by kvetoslavnovak** [comment]
Great 👍🏼 Thank you very much.
