### ISSUE TITLE
withMiddlewareAuth - Cannot find module '@supabase/auth-helpers-nextjs/middleware'

### ISSUE THREAD

**Issue by ferpintado** [supabase-community/auth-helpers#194]
I am trying to use `withMiddlewareAuth` in Next.js but seems like the module cannot be found.  I am migrating from the old `@supabase/supabase-auth-helpers` to the new packages and got the error.

Am I missing something?

Versions:

```
"@supabase/auth-helpers-nextjs": "^0.2.5",
"@supabase/auth-helpers-react": "^0.2.3",
"@supabase/supabase-js": "^1.35.4",
```

**Comment by ridhoadtyaa** [comment]
change to @supabase/auth-helpers-nextjs/dist/middleware

**Comment by ferpintado** [comment]
> change to @supabase/auth-helpers-nextjs/dist/middleware

This actually did not work, but I tried importing it from `@supabase/auth-helpers-nextjs/src/middleware` instead and it did not complain about the importer, however, when trying to access the route I got a compilation error:

![Screen Shot 2022-07-25 at 8 24 33 AM](https://user-images.githubusercontent.com/1950781/180816049-8df98810-bc1b-4b12-a38c-8b88f55a5790.png)

@mr-bjerre any thoughts?

**Comment by ferpintado** [comment]
> change to @supabase/auth-helpers-nextjs/dist/middleware

Thanks for the hint. It worked. 

The documentation needs to be updated. I'll create a PR

**Comment by ridhoadtyaa** [comment]
> > change to @supabase/auth-helpers-nextjs/dist/middleware
> 
> Thanks for the hint. It worked.
> 
> The documentation needs to be updated. I'll create a PR

what version of nextjs are you using?
I use withMiddlewareAuth, the user is logged in but still redirects to the login page, can't go to the dashboard
