### ISSUE TITLE
Need help accessing login page from authenticated routes causes flash of unprotected content and vice-versa

### ISSUE THREAD

**Issue by Bladeyy** [supabase-community/auth-helpers#198]
I'm an newbie in nextjs. I made an app that uses simple login, user page and a dashboard page ('/'). I used auth-helpers to protect my content from accessing by unathenticated users. All is fine. But there are two problems that I need to address.

1) Flash of unauthed cotent if I access /login page from dashboard page while being authenticated. 
2) Flash of authed content if I access /dahboard and any page that needs user from /login page.

Both scenarios are causing flash of authed/unauthed content. I solved this by using a page loader to show up during flash. But is it the best way? Can you tell me are there any other ways of protecting content that reduces need of pageloader? SSR can also be used but it's an overkill ig. Please guide me.

I using the solution of private component written here - [nextjs-redirect](https://theodorusclarence.com/blog/nextjs-redirect-no-flashing ) but it has a problem that is pageloader shows up everywhere when page refreshes for a split second.

I attached reddit website gif as an example to describe my problem. I'm accessing /settings page while not logged in and it shows up settings page for a split second before I get redirected to login. 

https://user-images.githubusercontent.com/40533936/181523068-bd04965a-b2b6-40c8-8008-d9a2dc5f22bb.mp4

**Comment by silentworks** [comment]
This question is better suited for https://github.com/supabase/supabase/discussions. The issue tracker here is to report bugs or make feature requests.
