### ISSUE TITLE
supabaseClient.auth.user() returns null with auth-helpers-sveltekit supabaseClient

### ISSUE THREAD

**Issue by kvetoslavnovak** [supabase-community/auth-helpers#199]
I have hard times to get a user using auth.user()  method using with supabaseClient  provided by auth-helpers-sveltekit .

Set up of the Supabase client:
```js
//  $lib/supabaseClient.js
import { createSupabaseClient } from '@supabase/auth-helpers-sveltekit';

const { supabaseClient } = createSupabaseClient(
	import.meta.env.VITE_SUPABASE_URL,
	import.meta.env.VITE_SUPABASE_ANON_KEY
);

export { supabaseClient };
```

Trying to use  supabaseClient.auth.user() in __layout.svelte
```js
// __layout.svelte
import { supabaseClient } from '$lib/sb';

async function supaUser() {
  const user = await supabaseClient.auth.user();
  console.log("user from supabase", user);
}

supaUser();
```
But only null comes back, even though I am getting the user using other possibilities like from store $session.user or in endpoints with locals.user.

**Comment by silentworks** [comment]
This would be because you aren't logged in at the time of checking for the user. The user that comes back from `$session.user` and `locals.user` are coming back from the cookie (which as it states could be stale).

**Comment by kvetoslavnovak** [comment]
It does not work even when I am already logged in and move from one page to another. 
Or do you think it is better to move to code to the hook.js for example?
Thank you very much.

**Comment by kvetoslavnovak** [comment]
I do not think this is the case. I can see sb-access-token and sb-refresh-token  right in my browser. I believe layout re calls ts function with every go to a new page.
