### ISSUE TITLE
Module not found: Can't resolve '@supabase/supabase-js'

### ISSUE THREAD

**Issue by ynnoj** [supabase-community/auth-helpers#204]
Initialising a new client in a Next.js project with TypeScript results in the following error ([source](https://github.com/supabase-community/auth-helpers/blob/e5dd556debd89f347c05ace6aa716d4e87cadf00/packages/nextjs/src/index.ts#L2)):
```
error - ./node_modules/@supabase/auth-helpers-nextjs/dist/index.js:58:0
Module not found: Can't resolve '@supabase/supabase-js'
```

Adding `@supabase/supabase-js` as a local `devDependency` remedies the issue. Seems it's only added as a `devDependency` in the [`package.json`](https://github.com/supabase-community/auth-helpers/blob/e5dd556debd89f347c05ace6aa716d4e87cadf00/packages/nextjs/package.json#L31).

**Comment by ynnoj** [comment]
I guess the docs assume you've already installed `@supbase/supabase-js` as a part of your project. Safe to ignore this 🤦

**Comment by meera** [comment]
Documentation assumes that supabase-js is installed. Documentation need to be explicit to add this. 

`yarn add @supabase/supabase-js 
`
