### ISSUE TITLE
service_role secret and createSupabaseClient from @supabase/auth-helpers-sveltekit?

### ISSUE THREAD

**Issue by kvetoslavnovak** [supabase-community/auth-helpers#211]
Using standard **createClient from '@supabase/supabase-js'** we are able to create supabase client with service_role secret. This is useful when we need to bypass Row Level Security, for example in my case I need to update profile of customer when Stripe webhook callback was received.  

Example:
```js
import { createClient } from "@supabase/supabase-js";
import dotenv from 'dotenv';

dotenv.config();

export const getServiceSupabase = () =>
createClient(
  import.meta.env.VITE_SUPABASE_URL,
  process.env['SUPABASE_SERVICE_KEY']
);
```
With **createSupabaseClient from '@supabase/auth-helpers-sveltekit'** this does not seem to work.

Failed example:
```js
import { createSupabaseClient } from '@supabase/auth-helpers-sveltekit';
import dotenv from 'dotenv';

dotenv.config();

export const getServiceSupabase = () =>
createSupabaseClient(
  import.meta.env.VITE_SUPABASE_URL,
  process.env['SUPABASE_SERVICE_KEY']
);
```

I can overcome this by creating two supabase clients. 

My question is weather @supabase/auth-helpers-sveltekit really does have the possibility to be used with the service_role secret to bypass Row Level Security.

Thank you very much.

**Comment by j4w8n** [comment]
I think they want you to import and use `supabaseServerClient` for that.

https://github.com/supabase-community/auth-helpers/blob/main/packages/sveltekit/README.md#server-side-data-fetching-with-rls

**Comment by kvetoslavnovak** [comment]
I have already tried supabaseServerClient. But it does not work in this case. supabaseServerClient has to be used with user`s session accessToken. But in this case there is only webhook from Stripe server requesting Supabase server. So you have no access to  accessToken. This process is server side and has to be server side because of the security reasons.

**Comment by silentworks** [comment]
You should do that without using this library. This library makes use of the returned object from `createSupabaseClient` in the client side which is somewhere you don't want your `service_key` to ever end up.

You can take a look at how I'm doing it in my waiting-list project, this is like my playground project for auth-helpers-sveltekit. https://github.com/silentworks/waiting-list/blob/main/src/lib/admin.js

**Comment by kvetoslavnovak** [comment]
[silentworks](https://github.com/silentworks) thank you very much for the tip.
