### ISSUE TITLE
NextJS: Email Auth sometimes do not work with RLS

### ISSUE THREAD

**Issue by rhalim-dev** [supabase-community/auth-helpers#212]
I'm running into a frustrating issue where I'm sometimes getting blocked by RLS errors when I try to login using email/password. Signing in is successful and I confirmed that the user is authenticated. Here is an example error. 

```
{message: "new row violates row-level security policy for table "vote"", code: "42501", details: null,…}
code: "42501"
details: null
hint: null
message: "new row violates row-level security policy for table \"vote\""
```

```
    "@supabase/auth-helpers-nextjs": "0.2.5",
    "@supabase/auth-helpers-react": "0.2.3",
    "@supabase/supabase-js": "1.35.4",
```

I don't think this is a RLS issue because using Google, FB, Twitter auth all works fine.

**Comment by silentworks** [comment]
This wouldn't be related to this library. If you are saying OAuth sign in works with RLS then there is no reason the email/password wouldn't work based on this library.

**Comment by rhalim-dev** [comment]
@silentworks Could you suggest me to what you think is the issue then? I initially thought this was a cookie/session issue so  I tried on multiple browsers with incognito mode and the issue still persists intermittently.
