### ISSUE TITLE
Move Supabase Auth component to supabase-auth-helpers

### ISSUE THREAD

**Issue by MildTomato** [supabase-community/auth-helpers#31]
Moving [Auth component](https://github.com/supabase/ui/tree/master/src/components/Auth) from Supabase UI to this repo.

We can start referring to the Auth component as 'Pre Built UI' (@thorwebdev ?), since we probably want to have it as an optional UI rather than a hard requirement for using Supabase Auth Helpers.

It might also be helpful to publish this on its own NPM package, in case anyone wants to directly use the pre built UI, without any of the framework-specific helpers (@thorwebdev ?)

After the component is moved into this repo, we can start developing a much more robust styling solution for the pre built UI.

**Comment by MildTomato** [comment]
Also mentioned [here](https://github.com/supabase/ui/issues/328)

**Comment by silentworks** [comment]
This has been moved to its own repo https://github.com/supabase-community/auth-ui
