### ISSUE TITLE
Module not found: Can't resolve 'next/dist/server/web/spec-extension/response'

### ISSUE THREAD

**Issue by Coci0AlexMeew** [supabase-community/auth-helpers#51]
Hi Supabase community. Awesome toolkit you have build here!

I found a bug when upgrading from v1.2.3 to v.1.3.0. 

It seems to be related to the new "withMiddleWareAuthRequired" helper:

`error - ./node_modules/@supabase/supabase-auth-helpers/nextjs/utils/withMiddlewareAuthRequired.js:6:0
Module not found: Can't resolve 'next/dist/server/web/spec-extension/response'`

The problem might be that we are using next 11 and you guys are using next 12.

Project Info:
- Expo sdk 44
- Next js 11.0.1
- Supabase js 1.30.7

**Comment by manucoffin** [comment]
Same issue here, with NextJs 11.1.0-0.45.3

**Comment by davut** [comment]
+1

**Comment by ashutoshrishi** [comment]
I am using `next@12.1.4` and `@supabase/supabase-auth-helpers@1.3.0` and facing the same issue, but with `ts-node` only.

Downgrading to `supabase-auth-helpers@1.2.3` works. It seems that ts-node follows this import and errors out:
https://github.com/supabase-community/supabase-auth-helpers/blob/7a275700b0db392c43b3e381ec801cc779a4dd54/src/nextjs/utils/withMiddlewareAuthRequired.ts#L2

The error being:

```
ReferenceError: Response is not defined
    at Object.<anonymous> (./node_modules/next/server/web/spec-extension/response.ts:10:35)
```

It's a NextJS app but I was using `ts-node` for transpiling the GraphQL API endpoint using [nexusjs](https://nexusjs.org/docs/) for GraphQL server type generation, as shown in the guide:
https://nexusjs.org/docs/getting-started/tutorial/chapter-setup-and-first-query.

The package.json script called:

    ts-node --transpile-only -P nexus.tsconfig.json pages/api/graphql

And the file `pages/api/graphql` imports and uses `withAuthRequired`, not even `withMiddlewareAuthRequired`.

**Comment by silentworks** [comment]
This version of the library is no longer maintained. Migrate to [@supabase/auth-helpers-nextjs](https://www.npmjs.com/package/@supabase/auth-helpers-nextjs).
