### ISSUE TITLE
Auth helpers for SvelteKit?

### ISSUE THREAD

**Issue by msdrigg** [supabase-community/auth-helpers#54]
Any plans to get auth helpers together for sveltekit?

**Comment by thorwebdev** [comment]
Yes, @silentworks is working on these 👍

**Comment by msdrigg** [comment]
Have you made any progress @silentworks

**Comment by ANorseDude** [comment]
Any info on this?

**Comment by silentworks** [comment]
This is currently working on the `add-sveltekit` branch, but I still need to create some helper functions and test it out in one of my real project. Hopefully there should be a version for everyone to play with by the end of next week.

**Comment by eetzkorn** [comment]
Amazing thank you @silentworks

**Comment by jordevorstenbosch** [comment]
@silentworks Is there anything you can use help with to get this show on the road?

Don't see any open issues relating to this, but I'd be glad to help in any way.

**Comment by gbarkhatov** [comment]
Hey @silentworks 
Any estimates on this?

**Comment by brandtam** [comment]
Looks like it's in the `next` branch now. Let me know if you want any help testing or writing docs @silentworks. It's looking great!

**Comment by silentworks** [comment]
@brandtam It would be really awesome if you could help with testing this out and also writing the docs. I'm currently creating the documentation skeleton out and will post on here once I have it all in the repo then we can start filling out each section with content.

**Comment by pablodavila95** [comment]
@silentworks I'm also testing it out. I'd be happy to help out with the docs @brandtam. 
Also, quick question: I'm using the provider token to make some API calls to Spotify but it seems like it expires and isn't autorefreshing. I'm using the autoRefresh prop in the <SupaAuthHelper/> from '@supabase/auth-helpers-svelte'.

**Comment by silentworks** [comment]
@pablodavila95 I think some code is missing around the `provider_token` side of the `auth-helpers-svelte` package. I will look into that this week and try to get a release out.

**Comment by david-plugge** [comment]
@silentworks is there a reason we have to add _src/routes/api/auth/user.ts_ and _src/routes/api/auth/callback.ts_? It could all be done within handle.

**Comment by oliver-lehner** [comment]
Is the README.md conclusive? Or are there additional steps to take to get data fetching to work?  I pasted the code from **Client-side data fetching with RLS** into an empty svelte file and followed all the other steps in the Read Me up to this section. I am using a magic link to authenticate. Only when I follow the magic link for the first time my RLS-protected data is on display. As soon as I refresh the page or follow the same link again `$session.user` has all the user data stored but `loadedData` is just an empty array. I'm learning SvelteKit and the authentication flow isn't easy for me to grasp. Is there an up-to-date example project for me to check out?

**Comment by silentworks** [comment]
> @silentworks is there a reason we have to add _src/routes/api/auth/user.ts_ and _src/routes/api/auth/callback.ts_? It could all be done within handle.

@david-plugge That's something worth exploring, a PR for that would be welcomed too.

**Comment by david-plugge** [comment]
i´ve created a PR #163

**Comment by silentworks** [comment]
Thanks for that PR @david-plugge. I'm closing this issue now and think any further SvelteKit auth helper related issues should all be created as new issues on this repo.
