### ISSUE TITLE
Expose `provider_token` in `getUser`

### ISSUE THREAD

**Issue by elliottetzkorn** [supabase-community/auth-helpers#55]
After signing in, the `supabaseClient.auth.session()` returns more data than it does after refreshing the page. After refreshing, all that is returned is the `access_token` and `type`. Even the `refresh_token` is gone. Is this a bug? I did not notice this when I implemented auth on my own. 

As far as I can tell that means that third party API's are only available server-side with this auth helper library. I would like to be able to call third party API's client side.

**Comment by thorwebdev** [comment]
Currently the provider_token is only persisted server-side in the `sb-provider-token` cookie (see [example](https://github.com/supabase-community/supabase-auth-helpers/blob/main/examples/nextjs/pages/github-provider-token.tsx)) .

Making the `provider-token` accessible on the user object is feasible. Let me investigate if there are any security concerns with it though. 

For now, would you be okay fetching third-party data server-side as shown in the example?

**Comment by eetzkorn** [comment]
Having to fetch this server side ads as much as a whole second of perceived latency to page loads - I do not think I can ship my website with this library as it's written

**Comment by thorwebdev** [comment]
For now you can add an api route that simply returns the value of the `sb-provider-token` cookie and then do the third-party data fetching client side.

**Comment by eetzkorn** [comment]
Yep that's exactly what I'm doing, even that simple fetch for `sb-provider-token` though can be really expensive on the response time. Sometimes it's very fast, other times it's up to a second. That's what I've observed at least.

**Comment by silentworks** [comment]
I've added a [`getProviderToken`](https://github.com/supabase-community/auth-helpers/blob/main/packages/nextjs/src/utils/getProviderToken.ts) method to retrieve this from the cookie. I know this isn't what you were asking for but this should suffice for now as returning the token in the user object could be a potential security issue.
