### ISSUE TITLE
Customize Auth component text with prop

### ISSUE THREAD

**Issue by mansoorsiddiqui** [supabase-community/auth-helpers#89]
Currently the text `Sign in with` in the Auth component is static:

<img width="333" alt="image" src="https://user-images.githubusercontent.com/13083500/166516208-e61a6aef-06cd-4205-bf50-3e4ba318b3f1.png">

Can we add a new prop so that we can customize the text? Maybe something like...
`<Auth signInText="Choose a sign in method:" />`

Or maybe even provide our own JSX...
`<Auth signInText={<SignInText/>} />`

**Comment by danielbichuetti** [comment]
Indeed this feature has a great impact on our choice. We are a legaltech startup focused on the Brazilian market initially. So we are deciding between another auth solution, or supabase if we can change texts. The whole solution, database and storage would be nice compared to our Azure solution being developed. It would let us focus on our business. But authentication in English is a problem for some of our clients.

**Comment by silentworks** [comment]
This component is no longer a part of this library
